# Generated by Django 2.1.3 on 2019-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190518_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='code',
            field=models.CharField(default=None, max_length=32, unique=True, verbose_name='Код приглашения'),
            preserve_default=False,
        ),
    ]
