# Generated by Django 2.1.3 on 2019-05-03 05:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=50, verbose_name='Инвентарный номер')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Характеристики')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_template', to='device.DeviceTemplate', verbose_name='Шаблон'),
        ),
    ]
