# Generated by Django 2.1.3 on 2019-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
