# Generated by Django 2.1.3 on 2019-05-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190503_0855'),
        ('device', '0002_auto_20190504_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Дата начала бронирования/обслуживания')),
                ('to_date', models.DateField(verbose_name='Дата окончания бронирования/обслуживания')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_reservations', to='device.Device', verbose_name='Оборудование')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_reservations', to='request.Request', verbose_name='Заявка')),
            ],
        ),
    ]
