# Generated by Django 2.1.3 on 2019-05-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='devicetemplate',
            options={'verbose_name': 'Шаблон оборудования', 'verbose_name_plural': 'Шаблоны оборудования'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронирование/обслуживание', 'verbose_name_plural': 'Бронирование/обслуживание'},
        ),
    ]
