# Generated by Django 2.1.3 on 2019-06-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190518_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=20000, verbose_name='Контент'),
        ),
    ]
