# Generated by Django 2.1.3 on 2019-05-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20190517_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreason',
            name='text',
            field=models.CharField(max_length=200, unique=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
