# Generated by Django 2.1.3 on 2019-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20190518_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='device_templates',
            field=models.ManyToManyField(blank=True, null=True, to='device.DeviceTemplate', verbose_name='Необходимое оборудование'),
        ),
    ]
