# Generated by Django 2.1.3 on 2019-06-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20190607_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='device_templates',
            field=models.ManyToManyField(blank=True, to='device.DeviceTemplate', verbose_name='Необходимое оборудование'),
        ),
    ]
